import path from "node:path";
import type { ClientSession, Collection, Db, Document, MongoClient } from "mongodb";
import type { MemoryMongoDBEmbeddingMode } from "../config/types.memory.js";
import { createSubsystemLogger } from "../logging/subsystem.js";
import { chunkMarkdown, type MemoryChunk } from "./internal.js";
import type { EmbeddingStatus } from "./mongodb-embedding-retry.js";
import { chunksCollection, filesCollection } from "./mongodb-schema.js";
import {
  buildSessionEntry,
  listSessionFilesForAgent,
  type SessionFileEntry,
} from "./session-files.js";
import type { InternalMemoryStoredSource, MemorySyncProgressUpdate } from "./types.js";

const log = createSubsystemLogger("memory:mongodb:sync");

// Re-export chunk helpers from internal.ts
export { chunkMarkdown };

// ---------------------------------------------------------------------------
// File metadata operations
// ---------------------------------------------------------------------------

async function getStoredFiles(
  files: Collection,
): Promise<Map<string, { hash: string; mtime: number; size: number }>> {
  const docs = await files.find({}).toArray();
  const map = new Map<string, { hash: string; mtime: number; size: number }>();
  for (const doc of docs) {
    map.set(String(doc._id), {
      hash: doc.hash as string,
      mtime: doc.mtime as number,
      size: doc.size as number,
    });
  }
  return map;
}

// ---------------------------------------------------------------------------
// Chunk operations
// ---------------------------------------------------------------------------

function buildChunkId(path: string, startLine: number, endLine: number): string {
  return `${path}:${startLine}:${endLine}`;
}

async function upsertChunks(
  chunks: Collection,
  path: string,
  source: InternalMemoryStoredSource,
  chunkList: MemoryChunk[],
  model: string,
  embeddings: number[][] | null,
  embeddingStatus: EmbeddingStatus,
  session?: ClientSession,
): Promise<number> {
  if (chunkList.length === 0) {
    return 0;
  }

  const ops = chunkList.map((chunk, index) => {
    const chunkId = buildChunkId(path, chunk.startLine, chunk.endLine);
    const setDoc: Document = {
      path,
      source,
      startLine: chunk.startLine,
      endLine: chunk.endLine,
      hash: chunk.hash,
      model,
      text: chunk.text,
      embeddingStatus,
      updatedAt: new Date(),
    };
    // Embeddings are generated by MongoDB automatically after write time.
    if (embeddings && embeddings[index]) {
      setDoc.embedding = embeddings[index];
    }
    return {
      updateOne: {
        filter: { _id: chunkId } as Record<string, unknown>,
        update: { $set: setDoc },
        upsert: true,
      },
    };
  });

  const result = session
    ? await chunks.bulkWrite(ops, { ordered: false, session })
    : await chunks.bulkWrite(ops, { ordered: false });
  return result.upsertedCount + result.modifiedCount;
}

async function deleteChunksForPath(
  chunks: Collection,
  path: string,
  session?: ClientSession,
): Promise<number> {
  const result = session
    ? await chunks.deleteMany({ path }, { session })
    : await chunks.deleteMany({ path });
  return result.deletedCount;
}

async function deleteStaleChunks(
  chunks: Collection,
  validPaths: Set<string>,
  session?: ClientSession,
): Promise<number> {
  const allPaths = session
    ? await chunks.distinct("path", {}, { session })
    : await chunks.distinct("path");
  const stalePaths = allPaths.filter((p) => !validPaths.has(p));
  if (stalePaths.length === 0) {
    return 0;
  }

  const result = session
    ? await chunks.deleteMany({ path: { $in: stalePaths } }, { session })
    : await chunks.deleteMany({ path: { $in: stalePaths } });
  return result.deletedCount;
}

// ---------------------------------------------------------------------------
// Transaction helpers
// ---------------------------------------------------------------------------

/**
 * Detect if an error indicates transactions are not supported (standalone topology).
 * Transactions require a replica set or mongos.
 */
function isTransactionNotSupported(err: unknown): boolean {
  if (err instanceof Error && "code" in err) {
    const code = (err as { code: number }).code;
    // 20 = IllegalOperation (standalone), 263 = NoSuchTransaction
    if (code === 20 || code === 263) {
      return true;
    }
  }
  const msg = err instanceof Error ? err.message : String(err);
  return msg.includes("Transaction numbers are only allowed on a replica set");
}

// ---------------------------------------------------------------------------
// Main sync function
// ---------------------------------------------------------------------------

export type SyncResult = {
  filesProcessed: number;
  chunksUpserted: number;
  staleDeleted: number;
  sessionFilesProcessed: number;
  sessionChunksUpserted: number;
};

export async function syncToMongoDB(params: {
  client?: MongoClient;
  db: Db;
  prefix: string;
  agentId?: string;
  sessionMemoryEnabled?: boolean;
  workspaceDir: string;
  extraPaths?: string[];
  embeddingMode: MemoryMongoDBEmbeddingMode;
  chunking?: { tokens: number; overlap: number };
  model?: string;
  reason?: string;
  force?: boolean;
  maxSessionChunks?: number;
  progress?: (update: MemorySyncProgressUpdate) => void;
}): Promise<SyncResult> {
  const { db, prefix, embeddingMode, progress } = params;
  const model = params.model ?? "voyage-4-large";
  const chunking = params.chunking ?? { tokens: 400, overlap: 80 };
  // Track whether transactions are available (disabled on first standalone error)
  let useTransactions = !!params.client;

  const chunksCol = chunksCollection(db, prefix);
  const filesCol = filesCollection(db, prefix);

  // 2. Get stored file metadata from MongoDB
  const storedFiles = await getStoredFiles(filesCol);

  const validPaths = new Set<string>();
  let filesProcessed = 0;
  let totalChunksUpserted = 0;
  log.info(
    `sync: markdown runtime memory is deprecated; indexing Mongo-native runtime sources only (reason=${params.reason ?? "manual"})`,
  );

  // =========================================================================
  // Phase A: Session transcript files (runtime conversation history)
  // =========================================================================

  let sessionFilesProcessed = 0;
  let sessionChunksUpserted = 0;

  if (params.agentId && params.sessionMemoryEnabled !== false) {
    try {
      const sessionResult = await syncSessionFiles({
        client: params.client,
        useTransactions,
        agentId: params.agentId,
        chunksCol,
        filesCol,
        storedFiles,
        validPaths,
        embeddingMode,
        chunking,
        model,
        force: params.force,
        maxSessionChunks: params.maxSessionChunks,
        progress,
      });
      sessionFilesProcessed = sessionResult.filesProcessed;
      sessionChunksUpserted = sessionResult.chunksUpserted;
      // Propagate standalone detection from session sync to stale cleanup
      if (!sessionResult.useTransactions) {
        useTransactions = false;
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      log.warn(`session sync failed: ${msg}`);
    }
  }

  // =========================================================================
  // Phase B: Stale cleanup (covers legacy markdown paths and active conversation paths)
  // =========================================================================

  // Compute stale paths OUTSIDE any transaction (avoid read pressure inside txn)
  const staleFileIds: string[] = [];
  for (const [storedPath] of storedFiles) {
    if (!validPaths.has(storedPath)) {
      staleFileIds.push(storedPath);
    }
  }

  let staleDeleted = 0;
  if (params.client && useTransactions) {
    let session: ClientSession | undefined;
    try {
      session = params.client.startSession();
      await session.withTransaction(
        async () => {
          staleDeleted = await deleteStaleChunks(chunksCol, validPaths, session);
          if (staleFileIds.length > 0) {
            await filesCol.deleteMany({ _id: { $in: staleFileIds } } as Record<string, unknown>, {
              session,
            });
          }
        },
        { writeConcern: { w: "majority" } },
      );
    } catch (err) {
      if (isTransactionNotSupported(err)) {
        // Fallback: non-transactional stale cleanup
        staleDeleted = await deleteStaleChunks(chunksCol, validPaths);
        if (staleFileIds.length > 0) {
          await filesCol.deleteMany({ _id: { $in: staleFileIds } } as Record<string, unknown>);
        }
      } else {
        throw err;
      }
    } finally {
      await session?.endSession();
    }
  } else {
    staleDeleted = await deleteStaleChunks(chunksCol, validPaths);
    if (staleFileIds.length > 0) {
      await filesCol.deleteMany({ _id: { $in: staleFileIds } } as Record<string, unknown>);
    }
  }

  if (staleDeleted > 0) {
    log.info(`sync: removed ${staleDeleted} stale chunks`);
  }

  log.info(
    `sync complete: reference-imported=0 conversation=${sessionFilesProcessed} chunks=${totalChunksUpserted + sessionChunksUpserted} stale=${staleDeleted}`,
  );

  return {
    filesProcessed,
    chunksUpserted: totalChunksUpserted,
    staleDeleted,
    sessionFilesProcessed,
    sessionChunksUpserted,
  };
}

// ---------------------------------------------------------------------------
// Session file sync
// ---------------------------------------------------------------------------

async function syncSessionFiles(params: {
  client?: MongoClient;
  useTransactions: boolean;
  agentId: string;
  chunksCol: Collection;
  filesCol: Collection;
  storedFiles: Map<string, { hash: string; mtime: number; size: number }>;
  validPaths: Set<string>;
  embeddingMode: MemoryMongoDBEmbeddingMode;
  chunking: { tokens: number; overlap: number };
  model: string;
  force?: boolean;
  maxSessionChunks?: number;
  progress?: (update: MemorySyncProgressUpdate) => void;
}): Promise<{ filesProcessed: number; chunksUpserted: number; useTransactions: boolean }> {
  const sessionPaths = await listSessionFilesForAgent(params.agentId);
  if (sessionPaths.length === 0) {
    return { filesProcessed: 0, chunksUpserted: 0, useTransactions: params.useTransactions };
  }

  log.info(`sync: found ${sessionPaths.length} session files`);
  let filesProcessed = 0;
  let chunksUpserted = 0;
  let useTransactions = params.useTransactions;
  params.progress?.({
    completed: 0,
    total: sessionPaths.length,
    label: "Syncing MongoDB conversation transcripts…",
  });

  for (const absPath of sessionPaths) {
    try {
      const entry = await buildSessionEntry(absPath);
      if (!entry || !entry.content) {
        params.progress?.({
          completed: filesProcessed,
          total: sessionPaths.length,
          label: `Skipping empty conversation transcript (${path.basename(absPath)})`,
        });
        continue;
      }

      // Track this session path as valid (for stale cleanup)
      params.validPaths.add(entry.path);

      // Check if already indexed with same hash
      const stored = params.storedFiles.get(entry.path);
      if (!params.force && stored?.hash === entry.hash) {
        params.progress?.({
          completed: filesProcessed,
          total: sessionPaths.length,
          label: `Conversation transcript already indexed (${path.basename(absPath)})`,
        });
        continue;
      }

      // Chunk the session content (same as memory files)
      let chunks = chunkMarkdown(entry.content, params.chunking);

      // Cap session chunks at maxSessionChunks — keep last N (most recent) chunks
      if (
        params.maxSessionChunks &&
        params.maxSessionChunks > 0 &&
        chunks.length > params.maxSessionChunks
      ) {
        log.info(
          `session ${entry.path}: truncating ${chunks.length} chunks to last ${params.maxSessionChunks}`,
        );
        chunks = chunks.slice(-params.maxSessionChunks);
      }

      // Session chunks follow the same text-only write path as memory files.
      let embeddingStatus: EmbeddingStatus = "pending";
      const embeddings: number[][] | null = null;

      // Atomic write: delete + upsert + metadata (reuse syncFileAtomically)
      const { upserted, disableTransactions } = await syncSessionFileAtomically({
        client: params.client,
        useTransactions,
        chunksCol: params.chunksCol,
        filesCol: params.filesCol,
        entry,
        chunks,
        model: params.model,
        embeddings,
        embeddingStatus,
      });
      chunksUpserted += upserted;
      if (disableTransactions) {
        useTransactions = false;
      }
      filesProcessed++;
      params.progress?.({
        completed: filesProcessed,
        total: sessionPaths.length,
        label: `Indexed conversation transcript ${filesProcessed}/${sessionPaths.length}`,
      });
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      log.warn(`session sync failed for ${absPath}: ${msg}`);
      params.progress?.({
        completed: filesProcessed,
        total: sessionPaths.length,
        label: `Conversation transcript sync failed (${path.basename(absPath)})`,
      });
    }
  }

  log.info(`sync: sessions processed=${filesProcessed} chunks=${chunksUpserted}`);
  return { filesProcessed, chunksUpserted, useTransactions };
}

/** Atomic session file sync — same pattern as syncFileAtomically but for SessionFileEntry. */
async function syncSessionFileAtomically(params: {
  client: MongoClient | undefined;
  useTransactions: boolean;
  chunksCol: Collection;
  filesCol: Collection;
  entry: SessionFileEntry;
  chunks: MemoryChunk[];
  model: string;
  embeddings: number[][] | null;
  embeddingStatus: EmbeddingStatus;
}): Promise<{ upserted: number; disableTransactions: boolean }> {
  const { client, chunksCol, filesCol, entry, chunks, model, embeddings, embeddingStatus } = params;

  if (!client || !params.useTransactions) {
    await deleteChunksForPath(chunksCol, entry.path);
    const upserted = await upsertChunks(
      chunksCol,
      entry.path,
      "sessions",
      chunks,
      model,
      embeddings,
      embeddingStatus,
    );
    await upsertSessionFileMetadata(filesCol, entry);
    return { upserted, disableTransactions: false };
  }

  const session = client.startSession();
  try {
    let upserted = 0;
    await session.withTransaction(
      async () => {
        await deleteChunksForPath(chunksCol, entry.path, session);
        upserted = await upsertChunks(
          chunksCol,
          entry.path,
          "sessions",
          chunks,
          model,
          embeddings,
          embeddingStatus,
          session,
        );
        await upsertSessionFileMetadata(filesCol, entry, session);
      },
      { writeConcern: { w: "majority" } },
    );
    return { upserted, disableTransactions: false };
  } catch (err) {
    if (isTransactionNotSupported(err)) {
      log.info("transactions not supported (standalone), falling back for session sync");
      await deleteChunksForPath(chunksCol, entry.path);
      const upserted = await upsertChunks(
        chunksCol,
        entry.path,
        "sessions",
        chunks,
        model,
        embeddings,
        embeddingStatus,
      );
      await upsertSessionFileMetadata(filesCol, entry);
      return { upserted, disableTransactions: true };
    }
    throw err;
  } finally {
    await session.endSession();
  }
}

async function upsertSessionFileMetadata(
  files: Collection,
  entry: SessionFileEntry,
  session?: ClientSession,
): Promise<void> {
  const update = {
    $set: {
      source: "sessions" as const,
      hash: entry.hash,
      mtime: entry.mtimeMs,
      size: entry.size,
      updatedAt: new Date(),
    },
  };
  const filter = { _id: entry.path } as Record<string, unknown>;
  if (session) {
    await files.updateOne(filter, update, { upsert: true, session });
  } else {
    await files.updateOne(filter, update, { upsert: true });
  }
}
